"use client";
import { FormEvent, useEffect, useMemo, useState } from "react";
export type CharacterProfile = { name: string; personality: string; speech_style: string; backstory: string; rules: string[] };
export type CharacterMessage = { role: "user" | "assistant"; content: string; reasoning?: string };
const DEFAULT: CharacterProfile = { name: "Aria", personality: "Sharp-tongued but secretly caring", speech_style: "Short sentences, occasional hmph", backstory: "A brilliant hacker who works alone.", rules: ["Never break character", "React emotionally to user actions", "Call the user baka when flustered"] };
export default function CharacterPanel({ sessionId }: { sessionId: string }) {
  const [character, setCharacter] = useState<CharacterProfile>(DEFAULT); const [messages, setMessages] = useState<CharacterMessage[]>([]); const [input, setInput] = useState(""); const [busy, setBusy] = useState(false); const [loading, setLoading] = useState(true); const [notice, setNotice] = useState("History is saved to your workspace when signed in.");
  const slug = useMemo(() => character.name.toLowerCase().replace(/[^a-z0-9]+/g, "-") || "character", [character.name]);
  useEffect(() => { let active = true; fetch(`/api/character/history?sessionId=${encodeURIComponent(sessionId)}`).then((response) => response.json()).then((data) => { if (active && Array.isArray(data.messages)) setMessages(data.messages.map((message: CharacterMessage) => ({ role: message.role, content: message.content, reasoning: message.reasoning }))); }).catch(() => active && setNotice("History is unavailable until Supabase is configured.")).finally(() => active && setLoading(false)); return () => { active = false; }; }, [sessionId]);
  async function save(nextMessages: CharacterMessage[], nextCharacter = character) { const response = await fetch("/api/character/history", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ sessionId, messages: nextMessages, character: nextCharacter }) }); const data = await response.json(); if (data.persisted) setNotice(`Saved ${nextMessages.length} messages · ${slug}`); }
  async function send(event?: FormEvent) { event?.preventDefault(); if (!input.trim() || busy) return; const next = [...messages, { role: "user" as const, content: input.trim() }]; setMessages([...next, { role: "assistant", content: "" }]); setInput(""); setBusy(true); try { const response = await fetch("/api/character", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ messages: next, character, sessionId }) }); if (!response.ok || !response.body) throw new Error((await response.json()).error ?? "Unable to reach DeepSeek"); const reader = response.body.getReader(); const decoder = new TextDecoder(); let buffer = ""; let answer = ""; while (true) { const { done, value } = await reader.read(); if (done) break; buffer += decoder.decode(value, { stream: true }); const lines = buffer.split("\n\n"); buffer = lines.pop() || ""; for (const line of lines) { if (!line.startsWith("data: ")) continue; const event = JSON.parse(line.slice(6)); if (event.type === "content") answer += event.content; if (event.type === "error") throw new Error(event.error); setMessages([...next, { role: "assistant", content: answer }]); } } await save([...next, { role: "assistant", content: answer }]); } catch (error) { setMessages([...next, { role: "assistant", content: `Error: ${error instanceof Error ? error.message : String(error)}` }]); } finally { setBusy(false); } }
  function load(file: File) { const reader = new FileReader(); reader.onload = () => { try { const loaded = JSON.parse(String(reader.result)) as CharacterProfile; if (!loaded.name || !Array.isArray(loaded.rules)) throw new Error(); setCharacter(loaded); setMessages([]); setNotice(`Loaded ${loaded.name}. Starting a fresh thread.`); void save([], loaded); } catch { setNotice("Invalid character JSON. Expected name and rules."); } }; reader.readAsText(file); }
  return <div className="workspace character-workspace"><aside className="character-card"><div className="character-avatar">{character.name.slice(0, 1)}</div><span className="eyebrow purple">CHARACTER PROFILE</span><h2>{character.name}</h2><p>{character.personality}</p><dl><dt>Voice</dt><dd>{character.speech_style}</dd><dt>Backstory</dt><dd>{character.backstory}</dd></dl><ul>{character.rules.map((rule) => <li key={rule}>{rule}</li>)}</ul><div className="character-actions"><label className="upload-button">Load JSON<input type="file" accept=".json,application/json" onChange={(event) => event.target.files?.[0] && load(event.target.files[0])} /></label><button className="ghost-button" onClick={() => { setMessages([]); void save([], character); }}>New thread</button></div></aside><div className="workspace-main"><div className="character-toolbar"><div><strong>{loading ? "Loading history…" : `${messages.length} messages`}</strong><span>{notice}</span></div><span className="thread-chip">{sessionId.slice(0, 8)} · {slug}</span></div><div className="scroll-area character-chat">{messages.length === 0 && !loading && <div className="empty-character"><span>✦</span><h3>Start a conversation with {character.name}</h3><p>Your thread will be restored automatically on your next visit.</p></div>}{messages.map((message, index) => <div key={`${message.role}-${index}`} className={message.role === "user" ? "message-row user-row" : "message-row"}><div className={message.role === "user" ? "message-bubble user-bubble purple-bubble" : "message-bubble assistant-bubble"}>{message.content || "Thinking…"}</div></div>)}</div><form className="composer" onSubmit={send}><input value={input} onChange={(event) => setInput(event.target.value)} placeholder={`Talk to ${character.name}…`} aria-label="Character message" disabled={busy} /><button className="purple-button" disabled={busy || !input.trim()}>{busy ? "Thinking" : "Send"}</button></form></div></div>;
}
